from __future__ import annotations

import datetime as dt
import os
import subprocess
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parent
DOCS_DIR = REPO_DIR / "docs"
LEDGER_PATH = DOCS_DIR / "BUILD_LEDGER.md"


def run_git(args: list[str]) -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(REPO_DIR), *args],
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
        )
        return out.strip()
    except subprocess.CalledProcessError as exc:
        return (exc.output or "").strip()


def file_exists(rel_path: str) -> bool:
    return (REPO_DIR / rel_path).exists()


def collect_components() -> list[tuple[str, str, bool]]:
    return [
        ("Control API", "agent_framework.py", file_exists("../agent_framework.py")),
        ("Telemetry/Data Engine", "../data_engine.py", file_exists("../data_engine.py")),
        ("Policy Engine", "../victor_core/policy.py", file_exists("../victor_core/policy.py")),
        ("Telegram Runtime", "telegram_server.py", file_exists("telegram_server.py")),
        ("Desktop Runtime", "desktop_server.py", file_exists("desktop_server.py")),
        ("Task Queue", "task_queue.py", file_exists("task_queue.py")),
        ("Orchestrator (PER)", "agent_orchestrator.py", file_exists("agent_orchestrator.py")),
        ("Tool Registry v2", "tool_registry_v2.py", file_exists("tool_registry_v2.py")),
        ("Local Router", "local_inference_router.py", file_exists("local_inference_router.py")),
        ("Training Pipeline", "training_pipeline.py", file_exists("training_pipeline.py")),
        ("Workflow Engine", "workflow_engine.py", file_exists("workflow_engine.py")),
        ("Voice Interface", "voice_interface.py", file_exists("voice_interface.py")),
        ("Browser Agent", "browser_agent.py", file_exists("browser_agent.py")),
        ("Skills Folder", "skills/", file_exists("skills")),
    ]


def format_status_lines(raw_status: str) -> list[str]:
    lines = [ln.rstrip() for ln in raw_status.splitlines() if ln.strip()]
    if not lines:
        return ["- Clean working tree"]
    return [f"- `{ln}`" for ln in lines]


def generate_markdown() -> str:
    now_utc = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    branch = run_git(["rev-parse", "--abbrev-ref", "HEAD"]) or "unknown"
    head_hash = run_git(["rev-parse", "--short", "HEAD"]) or "unknown"
    head_subject = run_git(["log", "-1", "--pretty=format:%s"]) or "unknown"
    head_author = run_git(["log", "-1", "--pretty=format:%an"]) or "unknown"
    head_date = run_git(["log", "-1", "--pretty=format:%ad", "--date=iso"]) or "unknown"
    recent_commits = run_git(["log", "--pretty=format:- `%h` | %ad | %an | %s", "--date=short", "-n", "25"])
    status_raw = run_git(["status", "--short"])
    tracked_count = run_git(["ls-files"]).splitlines()
    commit_count = run_git(["rev-list", "--count", "HEAD"])

    components = collect_components()
    component_lines = []
    for name, location, ok in components:
        mark = "OK" if ok else "MISSING"
        component_lines.append(f"- **{name}**: `{location}` [{mark}]")

    status_lines = format_status_lines(status_raw)
    if not recent_commits.strip():
        recent_commits = "- No commits found"

    return f"""# Victor Build Ledger

This is the living build log for Victor.  
It is auto-generated by `update_build_ledger.py`.

## Last Updated
- **Generated at**: {now_utc}
- **Branch**: `{branch}`
- **HEAD**: `{head_hash}` - {head_subject}
- **HEAD author/date**: {head_author} @ {head_date}

## Repository Snapshot
- **Tracked files**: {len(tracked_count)}
- **Total commits**: {commit_count}
- **Repo root**: `{REPO_DIR}`

## Implemented System Surface
{os.linesep.join(component_lines)}

## Recent Commits (Latest 25)
{recent_commits}

## Current Working Tree
{os.linesep.join(status_lines)}

## How This Stays Updated
1. Run manually: `python update_build_ledger.py`
2. Optional auto mode: `python install_build_ledger_hook.py` (installs post-commit hook)
3. After every commit, the hook refreshes this file.
"""


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    content = generate_markdown()
    LEDGER_PATH.write_text(content, encoding="utf-8")
    print(f"Updated: {LEDGER_PATH}")


if __name__ == "__main__":
    main()

